"""Central place for constants shared across the elbow tracking demo."""

DEFAULT_SAMPLE_RATE_HZ = 100.0
DEFAULT_CALIBRATION_DURATION_S = 3.0
DEFAULT_CALIBRATION_DURATION_FRAMES = int(DEFAULT_SAMPLE_RATE_HZ * DEFAULT_CALIBRATION_DURATION_S)
DEFAULT_ESTIMATOR = "simple"